"""Clean-clone reproducible test configuration. Every input resolves from an
explicit CLI option, an environment override, the repository's own tracked
canonical-evidence tree, or a session temporary directory. No default reaches
outside the repository checkout."""
import json, os, sys, pytest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))  # generator/ (package parent)
FROZEN_COMMIT = "6e86ac1955a0c566c7aae521705e51371992ba8a"
FROZEN_CACHE_DIR = f"repo-{FROZEN_COMMIT}"

def _first(cands):
    for c in cands:
        if c and os.path.exists(c): return os.path.abspath(c)
    return None

def pytest_addoption(parser):
    parser.addoption("--cache", default=None, help=f"pinned raw cache root ({FROZEN_CACHE_DIR})")
    parser.addoption("--importer", default=None, help="path to bench-import.py")

@pytest.fixture(scope="session")
def commit():
    return os.environ.get("DOMELAB_COMMIT", FROZEN_COMMIT)

@pytest.fixture(scope="session")
def cache(request):
    p = _first([request.config.getoption("--cache"), os.environ.get("DOMELAB_CACHE"),
        os.environ.get("DOMELAB_RAW_CACHE"),
        os.path.join(HERE, "..", "..", "canonical-evidence", "raw_cache",
                     FROZEN_CACHE_DIR)])
    if not p:
        pytest.fail("raw cache not found: pass --cache or set DOMELAB_CACHE; the "
                    f"repository ships it at canonical-evidence/raw_cache/{FROZEN_CACHE_DIR}",
                    pytrace=False)
    return p

@pytest.fixture(scope="session")
def staging_dir(tmp_path_factory, cache, commit):
    """Canonical-layout staging tree. DOMELAB_STAGING supplies the sealed
    epoch when available; otherwise a deterministic default-profile tree is
    generated into a session temporary directory and marked
    .session_generated so byte-seal gates know it is not the sealed epoch."""
    p = os.environ.get("DOMELAB_STAGING")
    if p and os.path.isdir(p):
        return os.path.abspath(p)
    from domelab_pipeline.pipeline import generate
    root = tmp_path_factory.mktemp("epoch_staging")
    out = os.path.join(str(root), "staging_canonical_6e86ac19")
    generate(cache, commit, out, write=True, run_parity=False)
    with open(os.path.join(out, ".session_generated"), "w", encoding="utf-8") as fh:
        fh.write("generated by the test session; not the sealed canonical epoch\n")
    return out

@pytest.fixture(scope="session")
def importer_path(request):
    p = _first([request.config.getoption("--importer"), os.environ.get("DOMELAB_IMPORTER"),
        os.path.join(HERE, "..", "..", "local_project", "bench-import.py")])
    if not p:
        pytest.skip("legacy bench-import.py is not part of this handoff; "
                    "set DOMELAB_IMPORTER or pass --importer to run the retired-importer gates")
    return p


@pytest.fixture(scope="session")
def review_staging(tmp_path_factory, cache, commit):
    """Full review-profile staging (viewer/picker/prose packs).

    The canonical epoch staging is evidence-only by definition and cannot
    contain UI surfaces, so UI-surface tests read a separately generated
    review-profile tree. Deterministic generation makes reuse safe; the tree
    is regenerated whenever the generator source identity changes."""
    p = os.environ.get("DOMELAB_REVIEW_STAGING")
    if p and os.path.isdir(p):
        return os.path.abspath(p)
    from domelab_pipeline.pipeline import (generate, generator_source_identity,
                                           parts_library_source_identity, _h)
    out = os.path.join(str(tmp_path_factory.mktemp("review_staging")), "tree")
    # every generator input affects the cache identity: scientific source
    # (.py) AND the parts-library presentation inputs (template + config);
    # the marker records the combined identity of what was generated
    ident = _h({"scientific": generator_source_identity(),
                "library": parts_library_source_identity()})
    generate(cache, commit, out, write=True, run_parity=False, viewer_profile="review")
    with open(os.path.join(out, ".source_identity"), "w", encoding="utf-8") as fh:
        fh.write(ident)
    return os.path.abspath(out)


@pytest.fixture(scope="session")
def sealed_epoch_source(staging_dir):
    """Guard for tests that byte-compare against the sealed canonical epoch.

    Those comparisons are only meaningful when the working generator source
    matches the identity recorded at the freeze; on an edited review branch
    they skip with direction instead of reporting a false regression."""
    import json as _json
    from domelab_pipeline.pipeline import generator_source_identity, _h
    if os.path.isfile(os.path.join(staging_dir, ".session_generated")):
        pytest.skip("canonical staging was generated in-session; supply the "
                    "sealed epoch via DOMELAB_STAGING to run byte-seal gates")
    meta = os.path.join(staging_dir, "schema_meta.staged.json")
    with open(meta, encoding="utf-8") as fh:
        sealed = _json.load(fh)["provenance_hashes"]["generator_source_hash"]
    if _h(generator_source_identity()) != sealed:
        pytest.skip("generator source differs from the sealed canonical epoch; "
                    "validate the frozen epoch from a pristine fc-3.4 worktree")
    return sealed

@pytest.fixture(scope="session")
def active_intake_identity():
    """Current importer/policy identity from the executable policy artifact."""
    path = os.path.join(HERE, "..", "domelab_pipeline", "config", "intake_policy.json")
    with open(path, encoding="utf-8") as stream:
        policy = json.load(stream)
    return {
        "policy_version": policy["policy_version"],
        "parity_target": policy["implementation_parity_target"],
    }
